### PR TITLE
[RAINCATCH-1239] Display and update workflow.version

### PR DESCRIPTION
**Pull request by paolobueno**
## Motivation
New workflow version field isn't being displayed in all instances.

Also during some update operations the version is not being bumped.

## Description
- Add display of workflow.version field along with workflow title for disambiguation
- Make sure all workflow updates bump the version to the next integer
- Add hooks to data service

### CODE REVIEW

**Comment by wtrocki** [comment]
@paolobueno - It's strange that we bumping version in the client, but I think we do not have much choice for the moment. 

I found issues:
- Version is missing from workflow edit screen
screen shot 2017-09-14 at 9 47 37 am
- Side list view is not updated after changing workflow. (Not sure if we can categorize that as refresh bug logged in separate ticket so wanted to mention)

**Comment by paolobueno** [comment]
@wtrocki I'd rather have the server update the versions automatically, I can change this to maybe only keep the pre/post hooks that might be useful for users and include a pr to core with that.

**Comment by wtrocki** [comment]
@paolobueno - I did not had strong feelings against that but I like your initiative. 
if that's not a problem we can really apply this to all models (not only workflows).

**Comment by wtrocki** [comment]
Rebase needed.

**Comment by paolobueno** [comment]
@wtrocki rebased :+1:

**Review by JameelB — APPROVED** [review]
verified locally

**Comment by paolobueno** [comment]
@JameelB thanks for verification!

**Pull request merged**
