### PR TITLE
[Feature] Mobile WFM with single workorder object

### PR DESCRIPTION
**Pull request by wtrocki**
## Motivation

WFM module code was migrated from previous solution. 
Most of the implementation is now spread across 3 main modules (WFM client, workflow, workorder). We need to simplify overal model to use single dataset. 
This will allow us to make other data improvements like having status attached to Workorders and fix some of the major issues in the current solution. 

TL;DR - mobile application should be based only on workorders (single dataset)

## Proposed changes

Workflow results can be merged into workorders and synced together.
Because of their nature workflows doesn't need to be synced. 
They aren't changing often and there is no chance of getting conflict.
Improvements to general step processing and UI framework
Enable duplication in step codes etc. 

## Progress

See core PR.

## Features that can be included

Add event based processing to monitor and connect to step progression (to be able to control and use branching functionality from code).

### CODE REVIEW

**Comment by wtrocki** [comment]
Current problem (workflow service is still required in mobile application due to using common modules). Angular requires those. We need to refactor api services to make dependency optional.

**Comment by wtrocki** [comment]
I think that we will need to remove interface for sync and rest api. Make rest api to be used directly in the modules and have common interface only for workorders

**Comment by wtrocki** [comment]
Adding steps to portal allows to render results. 
UI is little bit clunky, but it does the job.

screen shot 2017-09-03 at 2 51 21 am

**Comment by wtrocki** [comment]
Change ready for initial review. I think we may split this work to multiple PR's.

**Comment by paolobueno** [comment]
@wtrocki Right now I'll be doing
- [x] replacing usage of the apiservices with direct usage for workflows
- [x] replacing usage of the apiservices with direct usage for workorders

**Review by paolobueno — APPROVED** [review]

**Comment by wtrocki** [comment]
Verified locally! Great job!

**Pull request merged**
